### PR TITLE
Fix the activity list bottom blur

### LINKED ISSUE #227: Last item in the Drawer activity is blurred
### Description

See image 

Image

The bottom part is blurred (ok) to allow scrolling down, but the last item of the whole list (After completely scrolling down) is blurred, but it shouldn't be.

### Steps to reproduce

Make several operations so the Activity list has a scroll. When scrolling is available, the bottom appears blurred to indicate there are operations to scroll down to.

Once the user has scrolled to the bottom, the blur should dissapear, but it's there

### PR DESCRIPTION
**Pull request by gabmontes**
### Description

This PR solves the blur at the bottom of the activity list by 1) removing the bottom padding of the list container and 2) adding a bottom padding to the list itself. It also reduces the height of the blur overlay to match the empty space at the bottom of the list (6 bottom list padding + 3 bottom list item padding).

### Screenshots

https://github.com/user-attachments/assets/28bd4659-3b9f-45d4-b3f1-06820a180461

### Related issue(s)

Closes #227

### Checklist

- [x] Manual testing passed.
- [x] Automated tests added, or N/A.
- [x] Documentation updated, or N/A.
- [x] Environment variables set in CI, or N/A.

### CODE REVIEW

File: web/src/components/base/activityList/index.tsx [hunk 1]
```diff
@@ -14,7 +14,7 @@ export const ActivityList = ({
   onResetFilters,
 }: Props) =>
   items.length > 0 ? (
-    <div className="flex flex-col">
+    <div className="flex flex-col pb-6">
```
[the remark this answers is not in the document]
Comment (gabmontes) [reply web/src/components/base/activityList/index.tsx]: Ok.

File: web/src/components/walletDrawer/walletDrawerContent.tsx [hunk 2]
```diff
@@ -139,14 +139,14 @@ export function WalletDrawerContent() {
...
-          <div className="absolute inset-0 overflow-y-auto px-4 py-6 md:px-6">
+          <div className="absolute inset-0 overflow-y-auto px-4 pt-6 md:px-6">
             <ActivityList
               hasTransactions={activities.length > 0}
               items={itemsWithHref}
               onResetFilters={() => setSelectedFilters(allFilters)}
             />
           </div>
-          <div className="pointer-events-none absolute inset-x-0 bottom-0 h-34 bg-gradient-to-b from-transparent to-gray-50 to-80%" />
+          <div className="pointer-events-none absolute inset-x-0 bottom-0 h-9 bg-linear-to-b from-transparent to-gray-50 to-80%" />
```
[the remark this answers is not in the document]
Comment (gabmontes) [reply web/src/components/walletDrawer/walletDrawerContent.tsx]: No. Is ok.

**Review by dvnahuel — APPROVED** [review]
LGTM!

**Review by ArturDolzan — DISMISSED** [review]

File: web/src/components/walletDrawer/walletDrawerContent.tsx [hunk 3]
```diff
@@ -139,14 +139,15 @@ export function WalletDrawerContent() {
           />
         </div>
         <div className="relative min-h-0 flex-1 overflow-hidden">
-          <div className="absolute inset-0 overflow-y-auto px-4 py-6 md:px-6">
+          <div className="absolute inset-0 overflow-y-auto px-4 pt-6 md:px-6">
             <ActivityList
+              className="pb-6"
```
Comment (gndelia) [inline web/src/components/walletDrawer/walletDrawerContent.tsx]: This is the only usage of `ActivityList`. So I think we can just move `pb-6` to its inside implementation

**Review by gndelia — CHANGES_REQUESTED** [review]

File: web/src/components/walletDrawer/walletDrawerContent.tsx (hunk 3 above)
Comment (gabmontes) [reply web/src/components/walletDrawer/walletDrawerContent.tsx]: That was the first implementation but I think it is better to keep the ActivityList component clean and manage all the paddings in the same place at the container.

Comment (gndelia) [reply web/src/components/walletDrawer/walletDrawerContent.tsx]: then I'd do `*:pb-6` in the parent container. I never like that of adding `className` props and leave concatenating random classes which may collide with the internal implementation.

Comment (gabmontes) [reply web/src/components/walletDrawer/walletDrawerContent.tsx]: The only problem with that is the empty state, ActivityListEmptyState. And that shows the current architecture is flawed. Both the container and the overlay are part of ActivityList, not part of the container. So I moved those `div` and it is much more clean now.

**Review by ArturDolzan — APPROVED** [review]

**Review by gndelia — APPROVED** [review]
